# Generated by Django 5.0.6 on 2024-10-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=200)),
                ('gst_no', models.CharField(max_length=15)),
                ('mobile_no1', models.CharField(max_length=10)),
                ('mobile_no2', models.CharField(blank=True, max_length=10, null=True)),
                ('tracking_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('rv', models.DateTimeField(auto_now=True)),
                ('min_weight_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tpt_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_delete', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
