# Generated by Django 5.0.6 on 2024-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='min_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='min_weight_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='mobile_no1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='rv',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='tpt_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
