# Generated by Django 5.0.6 on 2024-10-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('transporter', '0005_alter_transporter_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
    ]
