# Generated by Django 5.1.1 on 2024-10-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning_activity_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('disable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_activity_category.planningactivitycategory')),
            ],
            options={
                'db_table': 'master_planning_activity',
            },
        ),
    ]
