# Generated by Django 5.0.6 on 2024-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_stage_name', models.CharField(max_length=50)),
                ('serial_no', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
