# Generated by Django 5.0.6 on 2024-10-18 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_alter_city_deleted_at_alter_city_deleted_by_and_more'),
        ('transporter', '0004_alter_transporter_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tpt_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ecc_charge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_adjustment_factor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('docket_fees', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rov', models.DecimalField(decimal_places=2, max_digits=18)),
                ('mcc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('oda', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ss', models.DecimalField(decimal_places=2, max_digits=18)),
                ('annual_hike', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rv', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_areas', to='city.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transporter_areas', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_areas', to='transporter.transporter')),
            ],
        ),
    ]
