# Generated by Django 5.0.6 on 2024-10-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='SerialStatus',
        ),
    ]
