# Generated by Django 5.0.6 on 2024-10-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='plus_minus',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=5),
        ),
    ]
