# Generated by Django 5.1.1 on 2024-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
