# Generated by Django 5.1.1 on 2024-09-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
