# Generated by Django 5.1.1 on 2024-09-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
