# Generated by Django 5.1.1 on 2024-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_type', '0002_permissiontype_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
