# Generated by Django 5.0.6 on 2024-10-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0005_alter_holidays_holiday_in_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayInArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('holiday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday.holidays')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
    ]
