# Generated by Django 5.0.6 on 2024-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_rename_title_produtcategory_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtcategory',
            old_name='created_by_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='produtcategory',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='produtcategory',
            old_name='deleted_by_user',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='produtcategory',
            old_name='date_deleted',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='produtcategory',
            old_name='updated_by_user',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='produtcategory',
            old_name='date_updated',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='produtcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
