# Generated by Django 5.0.6 on 2024-10-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_rename_deleted_at_state_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table=None,
        ),
    ]
