# Generated by Django 5.0.6 on 2024-10-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disable', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50)),
                ('brAddress', models.CharField(max_length=255)),
                ('brType', models.CharField(choices=[('HO', 'Head Office'), ('BR', 'Branch')], max_length=2)),
                ('isDealer', models.BooleanField(default=False)),
                ('contactNo', models.CharField(max_length=15)),
                ('isOTPValidation', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='state.state')),
            ],
        ),
    ]
