# Generated by Django 5.1.1 on 2024-10-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_action_taken', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masteractiontaken',
            table='action_taken',
        ),
    ]
