# Generated by Django 5.1.1 on 2024-10-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_action_taken', '0002_alter_masteractiontaken_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masteractiontaken',
            table='master_action_taken',
        ),
    ]
