# Generated by Django 5.0.6 on 2024-10-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
