# Generated by Django 5.0.6 on 2024-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Company Contact',
                'verbose_name_plural': 'Company Contacts',
                'db_table': 'company_contact',
                'ordering': ['company_name'],
            },
        ),
    ]
