# Generated by Django 5.0.6 on 2024-10-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customermaster',
            table='CustomerMaster',
        ),
    ]
