# Generated by Django 5.0.6 on 2024-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECCMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_from', models.DecimalField(decimal_places=2, max_digits=18)),
                ('weight_to', models.DecimalField(decimal_places=2, max_digits=18)),
                ('serial_no', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
