# Generated by Django 5.0.6 on 2024-10-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source_code', models.CharField(max_length=30)),
                ('lead_source_name', models.CharField(max_length=100)),
                ('is_lead_generate_by', models.BooleanField(default=False)),
                ('is_lead_assign_to', models.BooleanField(default=False)),
                ('is_re_generate_by', models.BooleanField(default=False)),
                ('is_re_assign_to', models.BooleanField(default=False)),
                ('is_lead_created_by', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rv', models.BinaryField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
