# Generated by Django 5.0.6 on 2024-10-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
