# Generated by Django 5.0.6 on 2024-10-08 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_mastergroup_delete_menu'),
        ('products', '0001_initial'),
        ('serial_status', '0002_rename_menu_serialstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('max_selling_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('min_discount', models.PositiveIntegerField()),
                ('warranty', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('disable', models.BooleanField(default=True)),
                ('tran_limit', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moq', models.PositiveIntegerField()),
                ('transfer_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_deleted', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.mastergroup')),
                ('serial_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serial_status.serialstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
