# Generated by Django 5.0.6 on 2024-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='min_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
