# Generated by Django 5.0.6 on 2024-10-22 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry_stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_study', models.CharField(blank=True, max_length=50, null=True)),
                ('enquiry_status_name', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('rv', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enquiry_statuses', to=settings.AUTH_USER_MODEL)),
                ('enquiry_stage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_statuses', to='enquiry_stage.enquirystage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enquiry_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
