# Generated by Django 5.0.6 on 2024-10-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('holidays_type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
