# Generated by Django 5.0.6 on 2024-10-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaystype',
            name='holidays_type',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
