# Generated by Django 5.0.6 on 2024-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_type', '0003_alter_holidaystype_holidays_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaystype',
            name='holidays_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
