# Generated by Django 5.1.1 on 2024-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='isRole',
            field=models.BooleanField(default=False, verbose_name='isRole'),
        ),
    ]
