# Generated by Django 5.0.6 on 2024-10-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('fms_stage', '0003_alter_fmsstage_created_by_alter_fmsstage_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FmsContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('rv', models.BinaryField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fms_contacts_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fms_contacts_deleted', to=settings.AUTH_USER_MODEL)),
                ('fms_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fms_stage.fmsstage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fms_contacts_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
