# Generated by Django 5.0.6 on 2024-10-15 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionYr', models.CharField(max_length=10, verbose_name='Session Year')),
                ('holiday_Name', models.CharField(max_length=255, verbose_name='Holiday Name')),
                ('holiday_date', models.DateField(verbose_name='Holiday Date')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('holidayType', models.CharField(choices=[('Public', 'Public Holiday'), ('Optional', 'Optional Holiday'), ('Religious', 'Religious Holiday'), ('National', 'National Holiday')], max_length=50, verbose_name='Holiday Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date')),
                ('createdBY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['holiday_date'],
            },
        ),
    ]
