# Generated by Django 5.0.6 on 2024-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_rename_createdby_holidays_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holiday_date',
            field=models.DateField(null=True, verbose_name='Holiday Date'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holiday_name',
            field=models.CharField(error_messages={'required': 'Holiday name is required.'}, max_length=255, verbose_name='Holiday Name'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='session_year',
            field=models.CharField(max_length=10, null=True, verbose_name='Session Year'),
        ),
    ]
