# Generated by Django 5.0.6 on 2024-10-16 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_alter_holidays_holiday_date_and_more'),
        ('holiday_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='holiday_in_area',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='holiday_type.holidaystype', verbose_name='Holiday in Area'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='holiday_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to='holiday_type.holidaystype', verbose_name='Holiday Type'),
        ),
    ]
