# Generated by Django 5.0.6 on 2024-10-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0004_holidays_holiday_in_area_alter_holidays_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='holiday_in_area',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='area.area', verbose_name='Holiday in Area'),
        ),
    ]
