# Generated by Django 5.0.6 on 2024-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0005_alter_holidays_holiday_in_area'),
        ('holiday_type', '0004_alter_holidaystype_holidays_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidays',
            unique_together={('holiday_type', 'holiday_in_area')},
        ),
    ]
