# Generated by Django 5.0.6 on 2024-10-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0006_alter_holidays_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidays',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='holiday_in_area',
        ),
        migrations.AddField(
            model_name='holidays',
            name='holiday_in_area',
            field=models.ManyToManyField(default=True, to='area.area', verbose_name='Holiday in Area'),
        ),
    ]
