# Generated by Django 5.0.6 on 2024-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_alter_holidays_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='session_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Session Year'),
        ),
    ]
