# Generated by Django 5.0.6 on 2024-10-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0008_alter_holidays_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='holiday_in_area',
        ),
        migrations.AddField(
            model_name='holidays',
            name='holiday_in_area',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='area.area', verbose_name='Holiday in Area'),
        ),
    ]
