# Generated by Django 5.0.6 on 2024-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('holiday', '0009_remove_holidays_holiday_in_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='holiday_in_area',
        ),
        migrations.AddField(
            model_name='holidays',
            name='holiday_in_area',
            field=models.ManyToManyField(blank=True, to='area.area', verbose_name='Holiday in Area'),
        ),
    ]
