# Generated by Django 5.0.6 on 2024-10-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_stage', '0001_initial'),
        ('pick_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmsstage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_stages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fmsstage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_stages_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fmsstage',
            name='tat_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pick_list.picklist'),
        ),
        migrations.AlterField(
            model_name='fmsstage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_stages_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
