# Generated by Django 5.0.6 on 2024-10-17 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_stage', '0002_alter_fmsstage_created_by_alter_fmsstage_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmsstage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_stages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fmsstage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_stages_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
