# Generated by Django 5.0.6 on 2024-10-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_mastergroup_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastergroup',
            old_name='categoryId',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='deletedBy',
            new_name='deleted_by',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='deletedDate',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='groupName',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='updatedBy',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='mastergroup',
            old_name='updatedDate',
            new_name='updated_date',
        ),
    ]
