# Generated by Django 5.1.1 on 2024-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('isRole', models.BooleanField(default=False, verbose_name='isRole')),
            ],
        ),
    ]
