# Generated by Django 5.0.6 on 2024-10-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pick_list_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_no', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pick_list.picklist')),
            ],
        ),
    ]
