# Generated by Django 5.1.1 on 2024-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateTimeField(blank=True, null=True)),
                ('ph_no', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('interest', models.DecimalField(decimal_places=3, max_digits=10)),
                ('alt_num', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('assign_to', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks1', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks2', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks3', models.CharField(blank=True, max_length=255, null=True)),
                ('enquiry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('enquiry_date', models.DateTimeField(blank=True, null=True)),
                ('enquiry_caller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calling_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_in_qualified_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('first_source', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_lead_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
