# Generated by Django 5.1.1 on 2024-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0002_interestedsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedsheet',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
