# Generated by Django 5.1.2 on 2024-10-16 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='mobile',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
