# Generated by Django 5.1.1 on 2024-09-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('permission_type', '0003_alter_permissiontype_name'),
        ('roles', '0002_alter_roles_isrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_type.permissiontype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles')),
            ],
            options={
                'unique_together': {('menu', 'role', 'permission_type')},
            },
        ),
    ]
